---
title: Brave the Skies
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  missions:
    title: Missions
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/logs/:title/"
    image:
    description:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: missions
  values:
    image:
    link:
permalink: pretty
repository: bravetheskies/siteleaf
url: https://bravetheskies.com
name: Brave the Skies
email: contact@bravetheskies.com
google_analytics: UA-10793928-1
twitter:
  username: bravetheskies
facebook:
  publisher: bravetheskies
logo: "/apple-touch-icon.png"
social:
links:
- https://twitter.com/bravetheskies
- https://www.facebook.com/bravetheskies
- https://www.linkedin.com/in/BenBalter
- https://plus.google.com/+bravetheskies
gems:
- jekyll-seo-tag
- jekyll-github-metadata
- jekyll-sitemap
- jekyll-feed
exclude:
- Gruntfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
